# docker-compose.redis.yml
services:
  redis:
    image: "redis:latest"
    container_name: "order-service-redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - order-service-network

networks:
  order-service-network:
    external: true

volumes:
  redis-data: