// <auto-generated />
using System;
using AuditSrvice.API.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditSrvice.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedRepository.Audit.Auditing", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("audt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditId"));

                    b.Property<string>("AuditJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audt_json");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("obj_nm");

                    b.Property<string>("ScreenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scr_nm");

                    b.Property<Guid>("ScreenPk")
                        .HasColumnType("uuid")
                        .HasColumnName("scr_pk");

                    b.HasKey("AuditId");

                    b.ToTable("audit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
